language: cpp
cache: ccache
services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      env: BUILD_DOCKER=yes
    - os: osx
      compiler: clang
      env:
        - CFLAGS="${CFLAGS} -std=c++11"
        - CXXFLAGS="${CXXFLAGS} -std=c++11"
    - os: linux
      compiler: gcc
      dist: bionic
      env: BUILD_DOCS=yes

addons:
  apt:
    packages:
      - epstool
      - ghostscript
      - gnuplot-nox
      - libav-tools
      - libgsl0-dev
      - liboctave-dev
      - make
      - pkg-config
      - pstoedit
      - swig3.0
      - texinfo
      - transfig
  homebrew:
    update: true
    brewfile: true

script:
  - git log -1
  - if test "${TRAVIS_OS_NAME}|${BUILD_DOCKER}" = "linux|yes"; then true
    && sudo docker build .
    ; fi
  - if test "${TRAVIS_OS_NAME}" = "osx"; then true
    && make SWIG=false
    ; fi
  - if test "${TRAVIS_OS_NAME}|${BUILD_DOCS}" = "linux|yes"; then true
    && make -j2 html
    ; fi
  - if test "${TRAVIS_OS_NAME}|${BUILD_DOCS}" = "linux|yes" && test "${TRAVIS_REPO_SLUG}" = "octapps/octapps" && test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_EVENT_TYPE}" = "push" && test "x${GITHUB_TOKEN}" != x; then true
    && echo -e "machine github.com\\nlogin kwwette\\npassword ${GITHUB_TOKEN}" > ~/.netrc
    && git clone https://github.com/octapps/octapps.github.io.git /tmp/octapps.github.io
    && rm -rf /tmp/octapps.github.io/*
    && mv -f html/* /tmp/octapps.github.io/
    && cd /tmp/octapps.github.io
    && git config user.name "${USER}"
    && git config user.email "<>"
    && git add --all
    && git commit --amend -C HEAD --date="`date -R`"
    && git push --force origin master
    && rm -f ~/.netrc
    ; fi
