language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: DOCKER=no
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: DOCKER=yes
    - os: osx
      compiler: clang
      env:
        - CFLAGS="${CFLAGS} -std=c++11"
        - CXXFLAGS="${CXXFLAGS} -std=c++11"
    - if: repo = octapps/octapps && branch = master
      os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: DOCUMENTATION=yes
  allow_failures:
    - os: linux
      env: DOCKER=no

stages:
  - name: deploy
    if: repo = octapps/octapps && branch = master

addons:
  apt:
    sources:
      - sourceline: "ppa:git-core/ppa"
      - sourceline: "ppa:kwwette/lscsoft"
      - sourceline: "deb https://packagecloud.io/github/git-lfs/ubuntu/ trusty main"
        key_url: "https://packagecloud.io/github/git-lfs/gpgkey"
    packages:
      - git-lfs
      - lalsuite-dev-deps
      - liboctave-dev
      - swig3.0
      - libgsl0-dev
      - libav-tools
      - texinfo
      - docker-ce
  homebrew:
    update: true
    brewfile: true

install:
  - if test "${TRAVIS_OS_NAME}|${DOCKER}" = "linux|no"; then true
    && ccache -s
    && git clone --depth=50 --branch=master https://git.ligo.org/lscsoft/lalsuite.git /tmp/lalsuite
    && pushd /tmp/lalsuite
    && ./00boot
    && ./configure --enable-cfitsio --enable-swig-octave --disable-swig-python --disable-all-lal --enable-lalframe --enable-lalpulsar --enable-lalapps
    && make -j2
    && make install
    && popd
    && source /tmp/lalsuite/_inst/etc/lalsuite-user-env.sh
    ; fi

script:
  - git log -1
  - if test "${TRAVIS_OS_NAME}|${DOCKER}" = "linux|no"; then true
    && make check NOSKIP=1 TESTS=funcName
    && make check NOSKIP=1 TESTS=src/general/funcName.m
    && make check NOSKIP=1 TESTDIR=src/general/
    && make -j2 check NOSKIP=1
    ; fi
  - if test "${TRAVIS_OS_NAME}|${DOCKER}" = "linux|yes"; then true
    && sudo docker build .
    ; fi
  - if test "${TRAVIS_OS_NAME}" = "osx"; then true
    && make SWIG=false
    ; fi
  - if test "${TRAVIS_OS_NAME}|${DOCUMENTATION}" = "linux|yes"; then true
    && make -j2 html
    ; fi

deploy:
  provider: pages
  on:
    repo: octapps/octapps
    branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: html/
  repo: octapps/octapps.github.io
  target-branch: master
  verbose: true
